---

name: 'Build JS'
description: 'Compile the TS source code'

inputs:
  npm-package:
    description: Build NPM package
    required: false
    default: 'false'

  django-staticfiles:
    description: Bundle Django staticfiles
    required: false
    default: 'false'

runs:
  using: 'composite'

  steps:

    - uses: actions/setup-node@v4
      with:
        node-version-file: 'js/.nvmrc'
        cache: npm
        cache-dependency-path: js/package-lock.json
        # Blocked by https://github.com/jazzband/django-cookie-consent/issues/120
        # registry-url: 'https://registry.npmjs.org'
        # scope: '@jazzband'

    - name: Install dependencies
      run: npm ci
      shell: bash
      working-directory: js

    - name: Build NPM package
      if: ${{ inputs.npm-package == 'true' }}
      run: npm run build
      shell: bash
      working-directory: js

    - name: Build Django assets package
      if: ${{ inputs.django-staticfiles == 'true' }}
      run: npm run build:django-static
      shell: bash
      working-directory: js
