name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    name: Publish packages
    runs-on: ubuntu-latest
    if: github.repository == 'jazzband/django-cookie-consent'

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install build twine

      - uses: ./.github/actions/build-js
        with:
          npm-package: 'true'
          django-staticfiles: 'true'

      - name: Build package
        run: |
          python -m build
          twine check dist/*

      - name: Upload packages to Jazzband private PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: jazzband
          password: ${{ secrets.JAZZBAND_RELEASE_KEY }}
          repository_url: https://jazzband.co/projects/django-cookie-consent/upload

      # Blocked on https://github.com/jazzband/django-cookie-consent/issues/120
      # - name: Publish NPM package to Github
      #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      #   run: npm publish
      #   working-directory: js
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
